input {
  tcp {
    port => 5000
    codec => json_lines
  }
  file {
    path => "/logs/*.log"
    start_position => "beginning"
    codec => json
    mode => "tail"
  }
}

filter {
  if ![service] {
    mutate { add_field => { "service" => "ai-blog-backend" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ai-blog-backend-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
